name: Flutter Workflow

on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'gradle'
          
      #- name: Get flutter version
      #  id: get_flutter_version
      # uses: its404/get-flutter-version@v1.0.0
      #- name: Output flutter version
      #  run: echo 'version_number:' ${{ steps.get_flutter_version.outputs.version_number }} ' build_number:' ${{ steps.get_flutter_version.outputs.build_number }}
          
      - name: Increment flutter build number
        uses: BentEngbers/flutter-change-version@v1.0.3
        
      #- name: Get flutter version
      #  id: get_flutter_versionn
      #  uses: its404/get-flutter-version@v1.0.0
      #- name: Output flutter version
      #  run: echo 'version_number:' ${{ steps.get_flutter_versionn.outputs.version_number }} ' build_number:' ${{ steps.get_flutter_versionn.outputs.build_number }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Make a build
        run: make just_build
