name: Flutter Workflow

on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'gradle'
          
      - name: Increment build number
        uses: BentEngbers/flutter-change-version@v1.0.3
        
      - name: Get new build number
        id: get_build_number
        uses: its404/get-flutter-version@v1.0.0
      #- name: Output flutter version
      #  run: echo 'version_number:' ${{ steps.get_flutter_versionn.outputs.version_number }} ' build_number:' ${{ steps.get_flutter_versionn.outputs.build_number }}
        
      - name: Set new app version
        uses: deusrobots/gh-action-flutter-pubspec-set-version@v1
        with:
          patch: ${{ steps.get_build_number.outputs.build_number }}
          
      - name: Get new app version
        id: get_app_version
        uses: its404/get-flutter-version@v1.0.0
        
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Make a build
        run: make just_build
        
      - name: Set current date as env variable
        run: echo "BUILD_DATE=$(date +'%d%m%Y')" >> $GITHUB_ENV
        
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{secrets.DRIVE_CREDENTIALS}}
          filename: build/app/outputs/flutter-apk/app-release.apk
          folderId: ${{secrets.UPLOAD_FOLDER_ID}}
          name: ${{ format('build_{0}_{1}.apk', steps.get_app_version.outputs.version_number, env.BUILD_DATE) }}
